name: Update Posts

on:
  workflow_dispatch:  # Allows manual triggering (or you could trigger it on a push, for example)
    inputs:
      postData:
        description: 'Post data to update'
        required: true
        type: string

jobs:
  update-posts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Decode the post data
      run: |
        echo "Post data: ${{ github.event.inputs.postData }}" > post_data.json

    - name: Update posts.json
      run: |
        curl -X PUT \
          -H "Authorization: token ${{ secrets.auth }}" \
          -H "Content-Type: application/json" \
          -d '{"message": "Add new post", "content": "$(base64 post_data.json)"}' \
          https://api.github.com/repos/unknown07724/postbox/contents/data/posts.json

    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add posts.json
        git commit -m "Update posts.json"
        git push origin main
