name: Update Posts

on:
  workflow_dispatch:
  repository_dispatch:
    types: [update-posts]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Update posts.json
        run: |
          echo '${{ github.event.client_payload.post }}' >> posts.json

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.auth }}
        run: |
          git add posts.json
          git commit -m "New post added via GitHub Actions"
          git push https://x-access-token:${{ secrets.auth }}@github.com/unknown07724/postbox.git
